apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dv4h2o8fe-go
  janus-idp.io/tekton: dv4h2o8fe-go
  backstage.io/kubernetes-id: dv4h2o8fe-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dv4h2o8fe-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
