apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dv4h2o8fe-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dv4h2o8fe-go 
  name: dv4h2o8fe-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dv4h2o8fe-go
    weight: 100 
